// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeAgentClient is the client API for NodeAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeAgentClient interface {
	// ── Discovery ──
	GetFullNodeInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FullNodeInfo, error)
	GetInstalledSoftware(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SoftwareList, error)
	// ── Real-time Monitoring ──
	StreamMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (NodeAgent_StreamMetricsClient, error)
	GetProcessList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProcessList, error)
	GetSystemLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (NodeAgent_GetSystemLogsClient, error)
	// ── Task Execution ──
	ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (NodeAgent_ExecuteTaskClient, error)
	CancelTask(ctx context.Context, in *TaskID, opts ...grpc.CallOption) (*CancelResponse, error)
	// ── File Transfer ──
	ReceiveFile(ctx context.Context, opts ...grpc.CallOption) (NodeAgent_ReceiveFileClient, error)
	SendFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (NodeAgent_SendFileClient, error)
	// ── Dependency Management ──
	CheckDependencies(ctx context.Context, in *DependencyList, opts ...grpc.CallOption) (*DependencyReport, error)
	InstallDependency(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (NodeAgent_InstallDependencyClient, error)
	// ── Health ──
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type nodeAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentClient(cc grpc.ClientConnInterface) NodeAgentClient {
	return &nodeAgentClient{cc}
}

func (c *nodeAgentClient) GetFullNodeInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FullNodeInfo, error) {
	out := new(FullNodeInfo)
	err := c.cc.Invoke(ctx, "/constellation.NodeAgent/GetFullNodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetInstalledSoftware(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SoftwareList, error) {
	out := new(SoftwareList)
	err := c.cc.Invoke(ctx, "/constellation.NodeAgent/GetInstalledSoftware", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) StreamMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (NodeAgent_StreamMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[0], "/constellation.NodeAgent/StreamMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeAgentStreamMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeAgent_StreamMetricsClient interface {
	Recv() (*NodeMetrics, error)
	grpc.ClientStream
}

type nodeAgentStreamMetricsClient struct {
	grpc.ClientStream
}

func (x *nodeAgentStreamMetricsClient) Recv() (*NodeMetrics, error) {
	m := new(NodeMetrics)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeAgentClient) GetProcessList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProcessList, error) {
	out := new(ProcessList)
	err := c.cc.Invoke(ctx, "/constellation.NodeAgent/GetProcessList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetSystemLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (NodeAgent_GetSystemLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[1], "/constellation.NodeAgent/GetSystemLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeAgentGetSystemLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeAgent_GetSystemLogsClient interface {
	Recv() (*LogEntry, error)
	grpc.ClientStream
}

type nodeAgentGetSystemLogsClient struct {
	grpc.ClientStream
}

func (x *nodeAgentGetSystemLogsClient) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeAgentClient) ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (NodeAgent_ExecuteTaskClient, error) {
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[2], "/constellation.NodeAgent/ExecuteTask", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeAgentExecuteTaskClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeAgent_ExecuteTaskClient interface {
	Recv() (*TaskProgress, error)
	grpc.ClientStream
}

type nodeAgentExecuteTaskClient struct {
	grpc.ClientStream
}

func (x *nodeAgentExecuteTaskClient) Recv() (*TaskProgress, error) {
	m := new(TaskProgress)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeAgentClient) CancelTask(ctx context.Context, in *TaskID, opts ...grpc.CallOption) (*CancelResponse, error) {
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, "/constellation.NodeAgent/CancelTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ReceiveFile(ctx context.Context, opts ...grpc.CallOption) (NodeAgent_ReceiveFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[3], "/constellation.NodeAgent/ReceiveFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeAgentReceiveFileClient{stream}
	return x, nil
}

type NodeAgent_ReceiveFileClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*FileReceipt, error)
	grpc.ClientStream
}

type nodeAgentReceiveFileClient struct {
	grpc.ClientStream
}

func (x *nodeAgentReceiveFileClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nodeAgentReceiveFileClient) CloseAndRecv() (*FileReceipt, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileReceipt)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeAgentClient) SendFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (NodeAgent_SendFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[4], "/constellation.NodeAgent/SendFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeAgentSendFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeAgent_SendFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type nodeAgentSendFileClient struct {
	grpc.ClientStream
}

func (x *nodeAgentSendFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeAgentClient) CheckDependencies(ctx context.Context, in *DependencyList, opts ...grpc.CallOption) (*DependencyReport, error) {
	out := new(DependencyReport)
	err := c.cc.Invoke(ctx, "/constellation.NodeAgent/CheckDependencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) InstallDependency(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (NodeAgent_InstallDependencyClient, error) {
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[5], "/constellation.NodeAgent/InstallDependency", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeAgentInstallDependencyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeAgent_InstallDependencyClient interface {
	Recv() (*InstallProgress, error)
	grpc.ClientStream
}

type nodeAgentInstallDependencyClient struct {
	grpc.ClientStream
}

func (x *nodeAgentInstallDependencyClient) Recv() (*InstallProgress, error) {
	m := new(InstallProgress)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeAgentClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/constellation.NodeAgent/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAgentServer is the server API for NodeAgent service.
// All implementations must embed UnimplementedNodeAgentServer
// for forward compatibility
type NodeAgentServer interface {
	// ── Discovery ──
	GetFullNodeInfo(context.Context, *Empty) (*FullNodeInfo, error)
	GetInstalledSoftware(context.Context, *Empty) (*SoftwareList, error)
	// ── Real-time Monitoring ──
	StreamMetrics(*MetricsRequest, NodeAgent_StreamMetricsServer) error
	GetProcessList(context.Context, *Empty) (*ProcessList, error)
	GetSystemLogs(*LogRequest, NodeAgent_GetSystemLogsServer) error
	// ── Task Execution ──
	ExecuteTask(*TaskRequest, NodeAgent_ExecuteTaskServer) error
	CancelTask(context.Context, *TaskID) (*CancelResponse, error)
	// ── File Transfer ──
	ReceiveFile(NodeAgent_ReceiveFileServer) error
	SendFile(*FileRequest, NodeAgent_SendFileServer) error
	// ── Dependency Management ──
	CheckDependencies(context.Context, *DependencyList) (*DependencyReport, error)
	InstallDependency(*InstallRequest, NodeAgent_InstallDependencyServer) error
	// ── Health ──
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedNodeAgentServer()
}

// UnimplementedNodeAgentServer must be embedded to have forward compatible implementations.
type UnimplementedNodeAgentServer struct {
}

func (UnimplementedNodeAgentServer) GetFullNodeInfo(context.Context, *Empty) (*FullNodeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullNodeInfo not implemented")
}
func (UnimplementedNodeAgentServer) GetInstalledSoftware(context.Context, *Empty) (*SoftwareList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstalledSoftware not implemented")
}
func (UnimplementedNodeAgentServer) StreamMetrics(*MetricsRequest, NodeAgent_StreamMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedNodeAgentServer) GetProcessList(context.Context, *Empty) (*ProcessList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessList not implemented")
}
func (UnimplementedNodeAgentServer) GetSystemLogs(*LogRequest, NodeAgent_GetSystemLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSystemLogs not implemented")
}
func (UnimplementedNodeAgentServer) ExecuteTask(*TaskRequest, NodeAgent_ExecuteTaskServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedNodeAgentServer) CancelTask(context.Context, *TaskID) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedNodeAgentServer) ReceiveFile(NodeAgent_ReceiveFileServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveFile not implemented")
}
func (UnimplementedNodeAgentServer) SendFile(*FileRequest, NodeAgent_SendFileServer) error {
	return status.Errorf(codes.Unimplemented, "method SendFile not implemented")
}
func (UnimplementedNodeAgentServer) CheckDependencies(context.Context, *DependencyList) (*DependencyReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDependencies not implemented")
}
func (UnimplementedNodeAgentServer) InstallDependency(*InstallRequest, NodeAgent_InstallDependencyServer) error {
	return status.Errorf(codes.Unimplemented, "method InstallDependency not implemented")
}
func (UnimplementedNodeAgentServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeAgentServer) mustEmbedUnimplementedNodeAgentServer() {}

// UnsafeNodeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServer will
// result in compilation errors.
type UnsafeNodeAgentServer interface {
	mustEmbedUnimplementedNodeAgentServer()
}

func RegisterNodeAgentServer(s grpc.ServiceRegistrar, srv NodeAgentServer) {
	s.RegisterService(&NodeAgent_ServiceDesc, srv)
}

func _NodeAgent_GetFullNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetFullNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/constellation.NodeAgent/GetFullNodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetFullNodeInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetInstalledSoftware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetInstalledSoftware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/constellation.NodeAgent/GetInstalledSoftware",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetInstalledSoftware(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).StreamMetrics(m, &nodeAgentStreamMetricsServer{stream})
}

type NodeAgent_StreamMetricsServer interface {
	Send(*NodeMetrics) error
	grpc.ServerStream
}

type nodeAgentStreamMetricsServer struct {
	grpc.ServerStream
}

func (x *nodeAgentStreamMetricsServer) Send(m *NodeMetrics) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeAgent_GetProcessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetProcessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/constellation.NodeAgent/GetProcessList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetProcessList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetSystemLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).GetSystemLogs(m, &nodeAgentGetSystemLogsServer{stream})
}

type NodeAgent_GetSystemLogsServer interface {
	Send(*LogEntry) error
	grpc.ServerStream
}

type nodeAgentGetSystemLogsServer struct {
	grpc.ServerStream
}

func (x *nodeAgentGetSystemLogsServer) Send(m *LogEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeAgent_ExecuteTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).ExecuteTask(m, &nodeAgentExecuteTaskServer{stream})
}

type NodeAgent_ExecuteTaskServer interface {
	Send(*TaskProgress) error
	grpc.ServerStream
}

type nodeAgentExecuteTaskServer struct {
	grpc.ServerStream
}

func (x *nodeAgentExecuteTaskServer) Send(m *TaskProgress) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeAgent_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/constellation.NodeAgent/CancelTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CancelTask(ctx, req.(*TaskID))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ReceiveFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServer).ReceiveFile(&nodeAgentReceiveFileServer{stream})
}

type NodeAgent_ReceiveFileServer interface {
	SendAndClose(*FileReceipt) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type nodeAgentReceiveFileServer struct {
	grpc.ServerStream
}

func (x *nodeAgentReceiveFileServer) SendAndClose(m *FileReceipt) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nodeAgentReceiveFileServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _NodeAgent_SendFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).SendFile(m, &nodeAgentSendFileServer{stream})
}

type NodeAgent_SendFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type nodeAgentSendFileServer struct {
	grpc.ServerStream
}

func (x *nodeAgentSendFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeAgent_CheckDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependencyList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CheckDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/constellation.NodeAgent/CheckDependencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CheckDependencies(ctx, req.(*DependencyList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_InstallDependency_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstallRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).InstallDependency(m, &nodeAgentInstallDependencyServer{stream})
}

type NodeAgent_InstallDependencyServer interface {
	Send(*InstallProgress) error
	grpc.ServerStream
}

type nodeAgentInstallDependencyServer struct {
	grpc.ServerStream
}

func (x *nodeAgentInstallDependencyServer) Send(m *InstallProgress) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeAgent_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/constellation.NodeAgent/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAgent_ServiceDesc is the grpc.ServiceDesc for NodeAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "constellation.NodeAgent",
	HandlerType: (*NodeAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullNodeInfo",
			Handler:    _NodeAgent_GetFullNodeInfo_Handler,
		},
		{
			MethodName: "GetInstalledSoftware",
			Handler:    _NodeAgent_GetInstalledSoftware_Handler,
		},
		{
			MethodName: "GetProcessList",
			Handler:    _NodeAgent_GetProcessList_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _NodeAgent_CancelTask_Handler,
		},
		{
			MethodName: "CheckDependencies",
			Handler:    _NodeAgent_CheckDependencies_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NodeAgent_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _NodeAgent_StreamMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSystemLogs",
			Handler:       _NodeAgent_GetSystemLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecuteTask",
			Handler:       _NodeAgent_ExecuteTask_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReceiveFile",
			Handler:       _NodeAgent_ReceiveFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendFile",
			Handler:       _NodeAgent_SendFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InstallDependency",
			Handler:       _NodeAgent_InstallDependency_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
