// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: cluster.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterServiceClient interface {
	// Node registration
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	DeregisterNode(ctx context.Context, in *DeregisterNodeRequest, opts ...grpc.CallOption) (*DeregisterNodeResponse, error)
	UpdateNodeInfo(ctx context.Context, in *UpdateNodeInfoRequest, opts ...grpc.CallOption) (*Empty, error)
	// Cluster info
	GetClusterInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ClusterInfo, error)
	GetComputationPool(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ComputationPool, error)
	// Heartbeat stream (agent → controller)
	HeartbeatStream(ctx context.Context, opts ...grpc.CallOption) (ClusterService_HeartbeatStreamClient, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, "/constellation.ClusterService/RegisterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) DeregisterNode(ctx context.Context, in *DeregisterNodeRequest, opts ...grpc.CallOption) (*DeregisterNodeResponse, error) {
	out := new(DeregisterNodeResponse)
	err := c.cc.Invoke(ctx, "/constellation.ClusterService/DeregisterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) UpdateNodeInfo(ctx context.Context, in *UpdateNodeInfoRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/constellation.ClusterService/UpdateNodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) GetClusterInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ClusterInfo, error) {
	out := new(ClusterInfo)
	err := c.cc.Invoke(ctx, "/constellation.ClusterService/GetClusterInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) GetComputationPool(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ComputationPool, error) {
	out := new(ComputationPool)
	err := c.cc.Invoke(ctx, "/constellation.ClusterService/GetComputationPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) HeartbeatStream(ctx context.Context, opts ...grpc.CallOption) (ClusterService_HeartbeatStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClusterService_ServiceDesc.Streams[0], "/constellation.ClusterService/HeartbeatStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterServiceHeartbeatStreamClient{stream}
	return x, nil
}

type ClusterService_HeartbeatStreamClient interface {
	Send(*HeartbeatRequest) error
	Recv() (*HeartbeatResponse, error)
	grpc.ClientStream
}

type clusterServiceHeartbeatStreamClient struct {
	grpc.ClientStream
}

func (x *clusterServiceHeartbeatStreamClient) Send(m *HeartbeatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterServiceHeartbeatStreamClient) Recv() (*HeartbeatResponse, error) {
	m := new(HeartbeatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterServiceServer is the server API for ClusterService service.
// All implementations must embed UnimplementedClusterServiceServer
// for forward compatibility
type ClusterServiceServer interface {
	// Node registration
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	DeregisterNode(context.Context, *DeregisterNodeRequest) (*DeregisterNodeResponse, error)
	UpdateNodeInfo(context.Context, *UpdateNodeInfoRequest) (*Empty, error)
	// Cluster info
	GetClusterInfo(context.Context, *Empty) (*ClusterInfo, error)
	GetComputationPool(context.Context, *Empty) (*ComputationPool, error)
	// Heartbeat stream (agent → controller)
	HeartbeatStream(ClusterService_HeartbeatStreamServer) error
	mustEmbedUnimplementedClusterServiceServer()
}

// UnimplementedClusterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClusterServiceServer struct {
}

func (UnimplementedClusterServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedClusterServiceServer) DeregisterNode(context.Context, *DeregisterNodeRequest) (*DeregisterNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeregisterNode not implemented")
}
func (UnimplementedClusterServiceServer) UpdateNodeInfo(context.Context, *UpdateNodeInfoRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeInfo not implemented")
}
func (UnimplementedClusterServiceServer) GetClusterInfo(context.Context, *Empty) (*ClusterInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterInfo not implemented")
}
func (UnimplementedClusterServiceServer) GetComputationPool(context.Context, *Empty) (*ComputationPool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComputationPool not implemented")
}
func (UnimplementedClusterServiceServer) HeartbeatStream(ClusterService_HeartbeatStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method HeartbeatStream not implemented")
}
func (UnimplementedClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/constellation.ClusterService/RegisterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_DeregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).DeregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/constellation.ClusterService/DeregisterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).DeregisterNode(ctx, req.(*DeregisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_UpdateNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).UpdateNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/constellation.ClusterService/UpdateNodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).UpdateNodeInfo(ctx, req.(*UpdateNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetClusterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetClusterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/constellation.ClusterService/GetClusterInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetClusterInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetComputationPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetComputationPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/constellation.ClusterService/GetComputationPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetComputationPool(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_HeartbeatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServiceServer).HeartbeatStream(&clusterServiceHeartbeatStreamServer{stream})
}

type ClusterService_HeartbeatStreamServer interface {
	Send(*HeartbeatResponse) error
	Recv() (*HeartbeatRequest, error)
	grpc.ServerStream
}

type clusterServiceHeartbeatStreamServer struct {
	grpc.ServerStream
}

func (x *clusterServiceHeartbeatStreamServer) Send(m *HeartbeatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clusterServiceHeartbeatStreamServer) Recv() (*HeartbeatRequest, error) {
	m := new(HeartbeatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "constellation.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _ClusterService_RegisterNode_Handler,
		},
		{
			MethodName: "DeregisterNode",
			Handler:    _ClusterService_DeregisterNode_Handler,
		},
		{
			MethodName: "UpdateNodeInfo",
			Handler:    _ClusterService_UpdateNodeInfo_Handler,
		},
		{
			MethodName: "GetClusterInfo",
			Handler:    _ClusterService_GetClusterInfo_Handler,
		},
		{
			MethodName: "GetComputationPool",
			Handler:    _ClusterService_GetComputationPool_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HeartbeatStream",
			Handler:       _ClusterService_HeartbeatStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cluster.proto",
}
